from django.urls import path
from . import views

urlpatterns = [
    path('home', views.home),

    path('districtregistration', views.districtregistration, name='districtregistration'),
    path('locationregistration', views.locationregistration, name='locationregistration'),
    path('materialregistration', views.materialregistration, name='materialregistration'),
    path('categoryregistration', views.categoryregistration, name='categoryregistration'),
    path('categoryexist', views.categoryexist, name='categoryexist'),
    path('sizeregistration', views.sizeregistration, name='sizeregistration'),
    path('submaterialregistration', views.submaterialregistration, name='submaterialregistration'),
    path('patternregistration', views.patternregistration, name='patternregistration'),
    path('fillsubmaterial', views.fillsubmaterial, name='fillsubmaterial'),
    path('colorregistration', views.colorregistration, name='colorregistration'),
    path('productregistration', views.productregistration, name='productregistration'),
    path('fillpattern', views.fillpattern, name='fillpattern'),
    path('purchase', views.purchase, name='purchase'),
    path('purchasemore', views.purchasemore, name='purchasemore'),

    path('viewdistrict', views.viewdistrict),
    path('viewmaterial', views.viewmaterial),
    path('viewcolor', views.viewcolor),
    path('viewcategory', views.viewcategory),
    path('viewsize', views.viewsize),
    path('fillsize', views.fillsize, name='fillsize'),
    path('viewlocation', views.viewlocation),
    path('filllocation', views.filllocation, name='filllocation'),
    path('viewsubmaterial', views.viewsubmaterial),
    path('fillsubmaterial', views.fillsubmaterial, name='fillsubmaterial'),
    path('viewpattern', views.viewpattern),
    path('fillpatternforview', views.fillpatternforview, name='fillpatternforview'),
    path('viewpurchase', views.viewpurchase),
    path('viewstock', views.viewstock),
    path('viewstockbymaterial', views.viewstockbymaterial),
    path('fillstock', views.fillstock, name='fillstock'),
    path('viewproduct', views.viewproduct),
    path('viewproductmorebyadmin/<id>', views.viewproductmorebyadmin, name='viewproductmorebyadmin'),
    path('viewproductbycategory', views.viewproductbycategory),
    path('fillproductbycategory', views.fillproductbycategory, name='fillproductbycategory'),
    path('viewproductbypattern', views.viewproductbypattern),
    path('fillproductbypattern', views.fillproductbypattern, name='fillproductbypattern'),
    path('viewshop', views.viewshop),
    path('viewshopmore/<id>', views.viewshopmore, name='viewshopmore'),
    path('viewbooking', views.viewbooking),
    path('viewbookingmore', views.viewbookingmore, name='viewbookingmore'),
    path('viewpayment', views.viewpayment),
    path('viewpaymentmore', views.viewpaymentmore, name='viewpaymentmore'),
    path('viewpurchasedetails/<id>', views.viewpurchasedetails, name='viewpurchasedetails'),
    path('viewpurchasedetailsmore/<id>', views.viewpurchasedetailsmore, name='viewpurchasedetailsmore'),
    path('viewstockmore/<id>', views.viewstockmore, name='viewstockmore'),
    path('viewshopbydistrict', views.viewshopbydistrict),
    path('fillshop', views.fillshop, name='fillshop'),
    path('viewreport', views.viewreport),
    path('viewreportbydate', views.viewreportbydate),
    path('fillreportbydate', views.fillreportbydate, name='fillreportbydate'),
    path('viewreportbydatemore/<id>', views.viewreportbydatemore, name='viewreportbydatemore'),
    path('viewreportbyproduct', views.viewreportbyproduct),
    path('viewreportbyproductmore/<id>', views.viewreportbyproductmore, name='viewreportbyproductmore'),
    path('viewreportbyshop', views.viewreportbyshop),
    path('viewreportbyshopmore/<id>', views.viewreportbyshopmore, name='viewreportbyshopmore'),
    path('export_excel/', views.ExportExcelShop.as_view(), name='export_excel'),
    path('piechart', views.pie_chart),

    path('deletedistrict/<id>', views.deletedistrict, name='deletedistrict'),
    path('deletematerial/<id>', views.deletematerial, name='deletematerial'),
    path('deletecolor/<id>', views.deletecolor, name='deletecolor'),
    path('deletelocation/<id>', views.deletelocation, name='deletelocation'),
    path('deletecategory/<id>', views.deletecategory, name='deletecategory'),
    path('deletesize/<id>', views.deletesize, name='deletesize'),
    path('deletesubmaterial/<id>', views.deletesubmaterial, name='deletesubmaterial'),
    path('deleteproduct/<id>', views.deleteproduct, name='deleteproduct'),
    path('deleteshop/<id>', views.deleteshop, name='deleteshop'),
    path('deletepattern/<id>', views.deletepattern, name='deletepattern'),
    path('deletebooking/<id>', views.deletebooking, name='deletebooking'),

    path('editdistrict/<id>', views.editdistrict, name='editdistrict'),
    path('editmaterial/<id>', views.editmaterial, name='editmaterial'),
    path('editcolor/<id>', views.editcolor, name='editcolor'),
    path('editlocation/<id>', views.editlocation, name='editlocation'),
    path('editcategory/<id>', views.editcategory, name='editcategory'),
    path('editsize/<id>', views.editsize, name='editsize'),
    path('editsubmaterial/<id>', views.editsubmaterial, name='editsubmaterial'),
    path('editproduct/<id>', views.editproduct, name='editproduct'),
    path('editpattern/<id>', views.editpattern, name='editpattern'),

    path('confirmbooking/<id>', views.confirmbooking, name='confirmbooking'),
]
