# Generated by Django 5.0.2 on 2024-02-28 18:02

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0017_alter_tblpurchase_purchasedate'),
        ('guestapp', '0008_alter_tblshop_registrationdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblbooking',
            fields=[
                ('bookingid', models.AutoField(primary_key=True, serialize=False)),
                ('bookingdate', models.DateField(default=datetime.date(2024, 2, 28))),
                ('deliverydate', models.DateField()),
                ('productid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='adminapp.tblproduct')),
            ],
        ),
        migrations.CreateModel(
            name='tblbookingdetails',
            fields=[
                ('bookingdetailsid', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.IntegerField(max_length=50)),
                ('bookingquantity', models.IntegerField(max_length=50)),
                ('bookingamount', models.IntegerField(max_length=50)),
                ('bookingid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='customerapp.tblbooking')),
                ('colorid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='adminapp.tblcolor')),
            ],
        ),
        migrations.CreateModel(
            name='tblpayment',
            fields=[
                ('paymentid', models.AutoField(primary_key=True, serialize=False)),
                ('paymentamount', models.IntegerField(max_length=50)),
                ('paymentdate', models.DateField(default=datetime.date(2024, 2, 28))),
                ('bookingid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='customerapp.tblbooking')),
                ('loginid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='guestapp.tbllogin')),
            ],
        ),
    ]
