# Generated by Django 5.0.2 on 2024-02-28 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0001_initial'),
        ('guestapp', '0008_alter_tblshop_registrationdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblbooking',
            name='bookingstatus',
            field=models.CharField(default=5, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tblbooking',
            name='loginid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='guestapp.tbllogin'),
        ),
    ]
