# Generated by Django 5.0.2 on 2024-03-03 07:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0002_tblbooking_bookingstatus_tblbooking_loginid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblbooking',
            name='bookingdate',
            field=models.DateField(default=datetime.date(2024, 3, 3)),
        ),
        migrations.AlterField(
            model_name='tblpayment',
            name='paymentdate',
            field=models.DateField(default=datetime.date(2024, 3, 3)),
        ),
    ]
