# Generated by Django 5.0.2 on 2024-03-05 20:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0005_alter_tblbookingdetails_sizeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblbooking',
            name='bookingdate',
            field=models.DateField(default=datetime.date(2024, 3, 6)),
        ),
        migrations.AlterField(
            model_name='tblpayment',
            name='paymentdate',
            field=models.DateField(default=datetime.date(2024, 3, 6)),
        ),
    ]
