# Generated by Django 5.0.3 on 2024-03-07 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0006_alter_tblbooking_bookingdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblbooking',
            name='bookingdate',
            field=models.DateField(default=datetime.date(2024, 3, 7)),
        ),
        migrations.AlterField(
            model_name='tblpayment',
            name='paymentdate',
            field=models.DateField(default=datetime.date(2024, 3, 7)),
        ),
    ]
