# Generated by Django 5.0.3 on 2024-03-09 17:52

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0007_alter_tblbooking_bookingdate_and_more'),
        ('guestapp', '0013_alter_tblshop_registrationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblbooking',
            name='bookingdate',
            field=models.DateField(default=datetime.date(2024, 3, 9)),
        ),
        migrations.AlterField(
            model_name='tblbooking',
            name='loginid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='guestapp.tblshop'),
        ),
        migrations.AlterField(
            model_name='tblpayment',
            name='paymentdate',
            field=models.DateField(default=datetime.date(2024, 3, 9)),
        ),
    ]
