# Generated by Django 5.0.3 on 2024-03-09 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0008_alter_tblbooking_bookingdate_and_more'),
        ('guestapp', '0013_alter_tblshop_registrationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblbooking',
            name='loginid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='guestapp.tbllogin'),
        ),
    ]
