# Generated by Django 5.0.3 on 2024-03-12 20:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0009_alter_tblbooking_loginid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblpayment',
            name='loginid',
        ),
        migrations.AlterField(
            model_name='tblbooking',
            name='bookingdate',
            field=models.DateField(default=datetime.date(2024, 3, 13)),
        ),
        migrations.AlterField(
            model_name='tblpayment',
            name='paymentdate',
            field=models.DateField(default=datetime.date(2024, 3, 13)),
        ),
    ]
