# Generated by Django 4.1 on 2024-02-18 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbllocation',
            fields=[
                ('locationid', models.AutoField(primary_key=True, serialize=False)),
                ('locationname', models.CharField(max_length=50)),
                ('districtid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbldistrict')),
            ],
        ),
    ]
