# Generated by Django 4.1 on 2024-02-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_tbllocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblmaterial',
            fields=[
                ('materialid', models.AutoField(primary_key=True, serialize=False)),
                ('materialtype', models.CharField(max_length=50)),
            ],
        ),
    ]
