# Generated by Django 4.1 on 2024-02-19 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_tblmaterial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblsubmaterial',
            fields=[
                ('submaterialid', models.AutoField(primary_key=True, serialize=False)),
                ('submaterialtype', models.CharField(max_length=50)),
                ('materialid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='adminapp.tblmaterial')),
            ],
        ),
    ]
