# Generated by Django 4.1 on 2024-02-19 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_tblsubmaterial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblpattern',
            fields=[
                ('patternid', models.AutoField(primary_key=True, serialize=False)),
                ('patternname', models.CharField(max_length=50)),
                ('patternphoto', models.ImageField(upload_to='')),
                ('submaterialid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='adminapp.tblsubmaterial')),
            ],
        ),
    ]
