# Generated by Django 4.1 on 2024-02-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_tblpattern'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblcolor',
            fields=[
                ('colorid', models.AutoField(primary_key=True, serialize=False)),
                ('colorname', models.CharField(max_length=50)),
            ],
        ),
    ]
