# Generated by Django 4.1 on 2024-02-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_tblproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblproduct',
            name='ideal',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
