# Generated by Django 4.1 on 2024-02-22 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_tblproduct_ideal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblproduct',
            old_name='description',
            new_name='desc',
        ),
    ]
