# Generated by Django 4.1 on 2024-02-22 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_rename_description_tblproduct_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblproduct',
            old_name='desc',
            new_name='description',
        ),
    ]
