# Generated by Django 4.1 on 2024-02-22 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_rename_desc_tblproduct_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblproduct',
            name='ideal',
        ),
    ]
