# Generated by Django 4.1 on 2024-02-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_remove_tblproduct_ideal'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblproduct',
            name='category',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
