# Generated by Django 4.1 on 2024-02-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0012_tblproduct_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblcategory',
            fields=[
                ('categoryid', models.AutoField(primary_key=True, serialize=False)),
                ('categoryname', models.CharField(max_length=50)),
            ],
        ),
    ]
