# Generated by Django 4.1 on 2024-02-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0013_tblcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblcategory',
            name='categoryphoto',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
