# Generated by Django 5.0.2 on 2024-02-23 09:48

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0014_tblcategory_categoryphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblpurchase',
            fields=[
                ('purchaseid', models.AutoField(primary_key=True, serialize=False)),
                ('billnumber', models.IntegerField(max_length=50)),
                ('purchaseamount', models.IntegerField(max_length=50)),
                ('discount', models.IntegerField(max_length=50)),
                ('purchasetotal', models.IntegerField(max_length=50)),
                ('purchasedate', models.DateField(default=datetime.date(2024, 2, 23))),
            ],
        ),
        migrations.CreateModel(
            name='tblpurchasedetails',
            fields=[
                ('purchasedetailsid', models.AutoField(primary_key=True, serialize=False)),
                ('purchasequantity', models.IntegerField(max_length=50)),
                ('colorid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='adminapp.tblcolor')),
                ('patternid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='adminapp.tblpattern')),
                ('purchaseid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='adminapp.tblpurchase')),
            ],
        ),
        migrations.CreateModel(
            name='tblstock',
            fields=[
                ('stockid', models.AutoField(primary_key=True, serialize=False)),
                ('stockquantity', models.IntegerField(max_length=50)),
                ('colorid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='adminapp.tblcolor')),
                ('patternid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='adminapp.tblpattern')),
            ],
        ),
    ]
