# Generated by Django 5.0.2 on 2024-02-26 18:15

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0015_tblpurchase_tblpurchasedetails_tblstock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblproduct',
            name='category',
        ),
        migrations.AddField(
            model_name='tblproduct',
            name='categoryid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='adminapp.tblcategory'),
        ),
        migrations.AlterField(
            model_name='tblpurchase',
            name='purchasedate',
            field=models.DateField(default=datetime.date(2024, 2, 26)),
        ),
    ]
