# Generated by Django 5.0.2 on 2024-02-28 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0016_remove_tblproduct_category_tblproduct_categoryid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblpurchase',
            name='purchasedate',
            field=models.DateField(default=datetime.date(2024, 2, 28)),
        ),
    ]
