# Generated by Django 5.0.2 on 2024-03-03 07:59

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0017_alter_tblpurchase_purchasedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblpurchase',
            name='purchasedate',
            field=models.DateField(default=datetime.date(2024, 3, 3)),
        ),
        migrations.CreateModel(
            name='tblsize',
            fields=[
                ('sizeid', models.AutoField(primary_key=True, serialize=False)),
                ('sizename', models.CharField(max_length=50)),
                ('categoryid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='adminapp.tblcategory')),
            ],
        ),
    ]
