# Generated by Django 5.0.2 on 2024-03-03 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0018_alter_tblpurchase_purchasedate_tblsize'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblproduct',
            name='categoryid',
        ),
        migrations.AddField(
            model_name='tblproduct',
            name='sizeid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='adminapp.tblsize'),
        ),
    ]
