# Generated by Django 5.0.2 on 2024-03-03 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0019_remove_tblproduct_categoryid_tblproduct_sizeid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblproduct',
            name='sizeid',
        ),
        migrations.AddField(
            model_name='tblproduct',
            name='categoryid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='adminapp.tblcategory'),
        ),
    ]
