# Generated by Django 5.0.2 on 2024-03-03 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0020_remove_tblproduct_sizeid_tblproduct_categoryid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblpurchase',
            name='purchasedate',
            field=models.DateField(default=datetime.date(2024, 3, 4)),
        ),
    ]
