# Generated by Django 5.0.2 on 2024-03-05 20:36

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0021_alter_tblpurchase_purchasedate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblsize',
            name='categoryid',
        ),
        migrations.AddField(
            model_name='tblsize',
            name='productid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='adminapp.tblproduct'),
        ),
        migrations.AddField(
            model_name='tblsize',
            name='sizequantity',
            field=models.IntegerField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tblpurchase',
            name='purchasedate',
            field=models.DateField(default=datetime.date(2024, 3, 6)),
        ),
    ]
