# Generated by Django 5.0.3 on 2024-03-07 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0022_remove_tblsize_categoryid_tblsize_productid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblsize',
            old_name='sizequantity',
            new_name='materialquantity',
        ),
        migrations.AlterField(
            model_name='tblpurchase',
            name='purchasedate',
            field=models.DateField(default=datetime.date(2024, 3, 7)),
        ),
    ]
