# Generated by Django 5.0.3 on 2024-03-09 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0023_rename_sizequantity_tblsize_materialquantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblpurchase',
            name='purchasedate',
            field=models.DateField(default=datetime.date(2024, 3, 9)),
        ),
    ]
