# Generated by Django 4.1 on 2024-02-18 17:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_tbllocation'),
        ('guestapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblshop',
            fields=[
                ('shopid', models.AutoField(primary_key=True, serialize=False)),
                ('shopname', models.CharField(max_length=50)),
                ('phone', models.BigIntegerField()),
                ('address', models.CharField(max_length=500)),
                ('shopphoto', models.ImageField(upload_to='')),
                ('registrationdate', models.DateField(default=datetime.date(2024, 2, 18))),
                ('locationid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbllocation')),
                ('loginid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='guestapp.tbllogin')),
            ],
        ),
    ]
