# Generated by Django 4.1 on 2024-02-19 18:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestapp', '0003_alter_tblshop_registrationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblshop',
            name='registrationdate',
            field=models.DateField(default=datetime.date(2024, 2, 20)),
        ),
    ]
