# Generated by Django 5.0.3 on 2024-03-07 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestapp', '0011_alter_tblshop_registrationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblshop',
            name='registrationdate',
            field=models.DateField(default=datetime.date(2024, 3, 7)),
        ),
    ]
